# Generated by Django 3.2 on 2023-01-19 15:32

from django.db import migrations, models
import django.db.models.deletion
import interview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('short_answer', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, null=True)),
                ('importance', models.IntegerField(validators=[interview.models.validate])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.category')),
            ],
        ),
    ]
